### ISSUE TITLE
Add new ERROR if a GTFS dataset has GTFS files in sub-folders

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1504] opened 2023-06-19 12:15 UTC
A [Pull Request](https://github.com/google/transit/pull/379) is currently open to explicitly forbid sub-folders in GTFS. 

It seems like there is a consensus on this issue and that the vote will be open shortly. 

It would be nice to add this validator rule before the vote opens because the result of the acceptance tests could inform on what practices currently exist around subfolders in GTFS.

The new rule notice has an ERROR severity level, and the pseudo-code is:
- if a GTFS input (zip file or URL) has sub-folders that contain .txt files from the spec ([full list in the navigation of gtfs.org here](https://gtfs.org/schedule/reference/#file-requirements)) then generate the notice. 

The PR to solve this issue should **not** be merged until [#379](https://github.com/google/transit/pull/379) passes successfully and is merged.

**Comment by emmambd** [comment] 2023-06-21 17:23
Modified the description based on [this clarification](https://github.com/google/transit/pull/379#issuecomment-1577499811). Subfolders are acceptable, but ones that contain GTFS files are not.

**Comment by qcdyx** [comment] 2023-07-03 20:03
Any thoughts on the naming of this error? @isabelle-dr @emmambd 

- invalid_GTFS_input
- invalid_input_with_subfolders
- invalid_GTFS_input_GTFS_files_in_subfolders
- invalid_input_GTFS_files_in_subfolders :woman-raising-hand:

**Comment by emmambd** [comment] 2023-07-04 13:25
@qcdyx I think the last one is the most accurate, but also not sure of the typical best practices we use in naming errors cc @isabelle-dr 

I've also updated the issue so it's clear that this PR should **not** be merged until #379 passes.

**Comment by qcdyx** [comment] 2023-07-12 15:43
Update:
1.invalid_input_files_in_subfolder is used for naming this error. The reason for not using invalid_input_GTFS_files_in_subfolders is that it would be changed to invalid_input_g_t_f_s_files_in_subfolder in the validation report and it's not that user friendly.
2. Mac created zip files reproduce the entire folder, for instance, test.zip contains a "test/" directory that contains the GTFS files and the validator generates missing_required_file notice. A new issue is created for this problem.
https://github.com/MobilityData/gtfs-validator/issues/1532
@emmambd @isabelle-dr

**Closed** 2023-07-25 18:25 UTC
Labels: GTFS Reference, status: Work in progress
