### ISSUE TITLE
foreign_key_violation doesn't catch a missing trip_id

### ISSUE THREAD

**Issue by tzujenchanmbd** [MobilityData/gtfs-validator#1752] opened 2024-05-09 03:03 UTC
### Describe the bug

When testing a feed with GTFS-flex data where there is a missing trip_id in trip.txt(parent file) but being referenced in stop_times.txt, validator doesn't show a `foreign_key_violation` error.

Here is the report link:
https://gtfs-validator-results.mobilitydata.org/83a0d446-3a65-4258-92c1-22b61c5dd6fe/report.html

### Steps/Code to Reproduce

1. Download the test feed provided below
2. Upload the feed to [Canonical GTFS Schedule Validator](https://gtfs-validator.mobilitydata.org/)

### Expected Results

Validator shows a `foreign_key_violation` error that indicates trip_id=t_5298041_b_77503_tn_0 in stop_times.txt cannot be found in trips.txt.

### Actual Results

Validator doesn't show the error

### Files used

[on-demand_services_between_multiple_zones.zip](https://github.com/MobilityData/gtfs-validator/files/15257002/on-demand_services_between_multiple_zones.zip)

### Validator version

5.0.1

### Operating system

MacOS

**Comment by qcdyx** [comment] 2024-05-16 19:00
<img width="822" alt="image" src="https://github.com/MobilityData/gtfs-validator/assets/5789435/36d1537c-0181-4bf9-822b-c8cb83ecc4ba">
I got too deep into analyzing the issue—it actually stems from a parsing error in the stop_times.txt file. Let's delve into how we can improve the presentation of this error for our end users.

**Comment by qcdyx** [comment] 2024-05-21 14:35
3 of the Flex gtfs data sets got parsing issues listed here https://docs.google.com/document/d/1QABoIeOdR6lAB7A6_X6WIbZwC7EnAIZvm_hRNwNQeoI/edit#heading=h.xt9phhoxqouq
New issue created https://github.com/MobilityData/gtfs-validator/issues/1767

**Comment by cka-y** [comment] 2024-10-02 16:13
Closing this as the issue is not reproducible. I was able to observe the foreign key error notice for the specified example feed and trip ID.

![Image](https://github.com/user-attachments/assets/b26b2a7d-8b73-49b4-9bcd-dc42d9386442)

**Closed by cka-y** 2024-10-02 16:13 UTC
Labels: bug

**Comment by emmambd** [comment] 2024-10-07 13:17
Wondering if this works now because of other modifications we've made so Flex feeds are parseable. Regardless, glad to see this is corrected.
