### ISSUE TITLE
[BUG] Validator unable to execute when agency_ID is missing.

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#396] opened 2020-09-30 19:55 UTC
**Describe the bug**
The validator was unable to process a feed and gave an error.

**To Reproduce**
Run the validator on the following dataset: http://transitfeeds.com/p/long-beach-transit/704/latest/download

**Expected behavior**
No notice should be generated in this case.

**Witnessed behavior**
Upon running the validator, I received this message before the operation ended.
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "this.agencyId" is null
	at org.mobilitydata.gtfsvalidator.domain.entity.gtfs.routes.Route$RouteBuilder.build(Route.java:281)
	at org.mobilitydata.gtfsvalidator.usecase.ProcessParsedRoute.execute(ProcessParsedRoute.java:80)
	at org.mobilitydata.gtfsvalidator.Main.lambda$main$0(Main.java:113)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.mobilitydata.gtfsvalidator.Main.main(Main.java:94)
```

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: v1.2.2

**Additional context**
The agency_ID field only appears in the agency.txt file.

**Comment by mcplanner** [comment] 2020-09-30 20:00
Corrected MD formatting

**Comment by fabrice-v** [comment] 2020-09-30 20:30
Duplicate of #378 

Fix already available in the latest snapshot version, see https://github.com/MobilityData/gtfs-validator/actions

**Closed by fabrice-v** 2020-09-30 20:30 UTC
