### ISSUE TITLE
When using CLI in windows, invalid path exception is always thrown

### ISSUE THREAD

**Issue by LuisDiezLaso** [MobilityData/gtfs-validator#1158] opened 2022-05-19 10:33 UTC
## **Bug report** 

The GTFS Validator IN WINDOWS 10(this probably doesn´t happen for linux) seems to always throw an InvalidPathException for the input file path.
This didn´t happen in [release 3.0.1](https://github.com/MobilityData/gtfs-validator/releases/tag/v3.0.1)

**Describe the bug**
The GTFS Validator throws InvalidPathException in Windows no matter what the path of the input file is.

**How we reproduce the bug**
All of these steps are being reproduced in the jar for windows and java 11 from [one of your latest pushes to master](https://github.com/MobilityData/gtfs-validator/actions/runs/2339315510)
1. Try to execute the jar with any input file.
![image](https://user-images.githubusercontent.com/45883071/169271587-53740890-4339-469d-9f48-fc5eafad3c02.png)

2. U should get an error like this.
![image](https://user-images.githubusercontent.com/45883071/169271113-c6500002-d4cb-4bfb-8fc3-ca4c931f4408.png)

3. As you can see in the error, there is one extra "/" character in the beginning of the path which throws the exception, maybe you are trying to build a path from the CLI arguments, from that path take the URI, and then from the URI build the path back again and that just leaves a special character in windows systems.

**Expected behaviour**
It shouldn´t throw an exception when the given path is fine.
**Observed behaviour**
There´s an exception thrown.

**Screenshots:** 
The ones above explain the issue(if they don´t, just let me know).

**Environment versions**
- validator version: used jar from [one of your latest pushes to master](https://github.com/MobilityData/gtfs-validator/actions/runs/2339315510)
- Java version: 11.0.15
- OS versions: Windows 10

**Comment by isabelle-dr** [comment] 2022-05-19 13:15
👋 Hello @LuisDiezLaso , thanks for opening this issue! 

This looks like it might have happened in one of our latest PRs. Our team will have a look at where this might have come from :)
I tested the validator with the JAR from the PR you linked and it worked on my Mac M1 (I used the `ubuntu-latest` [gtfs-validator-v-master-sha-57813dd3-SNAPSHOT_cli.jar](https://github.com/MobilityData/gtfs-validator/suites/6542236707/artifacts/244202931)).

By the way, the changes that have been made since v3.0.1 don't impact the rules and/or the validation report: it adds a [packaged EXE & HTML output](https://github.com/MobilityData/gtfs-validator/issues/1124), so the validation report you would have gotten with this latest JAR wouldn't have been any different! You just would have been able to see it in HTML.

**Comment by barbeau** [comment] 2022-05-19 16:20
I've opened PR https://github.com/MobilityData/gtfs-validator/pull/1160 to fix this.

The issue is also fixed in PR https://github.com/MobilityData/gtfs-validator/pull/1146 (I ran into it when testing that PR), but I've opened https://github.com/MobilityData/gtfs-validator/pull/1160 for traceability and because I don't know how much more review is planned for https://github.com/MobilityData/gtfs-validator/pull/1146.

**Comment by barbeau** [comment] 2022-05-20 13:16
https://github.com/MobilityData/gtfs-validator/pull/1146 was merged first, so this issue should be fixed now in the main branch as https://github.com/MobilityData/gtfs-validator/pull/1146 contained a fix as well.

 @LuisDiezLaso Could you give the current main branch a try and let us know if you still have problems?

**Closed by barbeau** 2022-05-20 13:16 UTC
Labels: bug

**Comment by LuisDiezLaso** [comment] 2022-05-25 11:18
@barbeau The main branch is working fine, it seems like this issue is fixed
