### ISSUE TITLE
Check whether expired services (calendars) exist on schedule feed

### ISSUE THREAD

**Issue by owades** [MobilityData/gtfs-validator#1279] opened 2022-10-18 21:59 UTC
### Describe the problem

The [GTFS Best Practices](https://gtfs.org/schedule/best-practices/) include the following best practice:

`Remove old services (expired calendars) from the feed.`

We don't have a check that looks for expired calendars

### Describe the new validation rule

If there exists a row in calendar.txt with end_date < TODAY_DATE, or a row in calendar_dates.txt with date < TODAY_DATE, trigger an "expired_calendar" notice

### Severity

Warning

**Comment by isabelle-dr** [comment] 2022-11-03 15:35
This sounds good, thanks for opening this!

**Comment by bradyhunsaker** [comment] 2023-03-01 03:32
I will give this a try. I am inclined to rename the file MissingCalendarAndCalendarDateValidator.java as CalendarAndCalendarDateValidator.java and include these checks there.

Any concerns about renaming a file like that?

**Comment by isabelle-dr** [comment] 2023-03-03 22:42
No concerns, you can go ahead.
(cc @bdferris-v2)

**Comment by bradyhunsaker** [comment] 2023-03-10 12:50
I was working on this, but I just realized I think it is a duplicate of (part of) https://github.com/MobilityData/gtfs-validator/issues/886
Could you confirm that?

**Comment by isabelle-dr** [comment] 2023-03-10 16:52
You are right, this issue looks like the second portion of #886! 
Please note that @KClough started to work on this in #1289

**Closed** 2023-03-10 16:53 UTC
Labels: GTFS Best Practices, status: Ready, new rule
