### ISSUE TITLE
Including networks, route_networks files causing false positive errors

### ISSUE THREAD

**Issue by evansiroky** [MobilityData/gtfs-validator#1756] opened 2024-05-11 00:27 UTC
### Describe the bug

The GTFS Schedule validator flags a false positive `foreign_key_violation` error upon validating a GTFS feed that includes the `networks.txt` and `route_networks.txt` files. 

### Steps/Code to Reproduce

Try to validate the following minimally reproducable GTFS feed here: [test GTFS.zip](https://github.com/MobilityData/gtfs-validator/files/15281016/test.GTFS.zip).

### Expected Results

No errors are raised.

### Actual Results

A single `foreign_key_violation` error is raised.

### Validator version

5.0.1

### Operating system

Web-based validator tool.

**Comment by qcdyx** [comment] 2024-05-16 15:47
Hello @evansiroky thanks for reporting this issue. If you take a closer look at the description of the foreign_key_violation notice, you can find it's not about networks.txt and route_networks.txt. It says that fare_leg_rules.txt has a network_id "Bus", but not found in the parent file routes.txt which contains route_ids 1, 1, 3. cc @tzujenchanmbd 

<img width="1697" alt="image" src="https://github.com/MobilityData/gtfs-validator/assets/5789435/f3baeb87-b0de-4e1b-9f42-ab51be597a14">

**Comment by qcdyx** [comment] 2024-05-17 14:52
Ok, I see what you mean. https://github.com/MobilityData/gtfs-validator/issues/1764
cc @tzujenchanmbd

**Comment by qcdyx** [comment] 2024-06-12 13:59
Close this issue since it's a duplicate of #1764

**Comment by emmambd** [comment] 2024-08-28 17:42
Hi @evansiroky! Thanks for flagging this issue - it's resolved in #1764 and will be a part of our next validator release.

**Closed by emmambd** 2024-08-28 17:42 UTC
Labels: bug, status: Ready
