### ISSUE TITLE
Implement transfer distance verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#157] opened 2020-05-04 15:27 UTC
**Is your feature request related to a problem? Please describe.**
Transfer distance should not be too large. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as  TYPE_TRANSFER_DISTANCE_IS_VERY_LARGE.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies transfer distance; if more than 10 000, it causes an error, if more than 2000, it causes a warning.

**Describe alternatives you've considered**

**Additional context**
Line 121 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment] 2020-05-07 15:59
Another threshold that's not in the spec or best practices

**Comment by isabelle-dr** [comment] 2022-12-17 23:20
Closing, duplicate of #203

**Closed by isabelle-dr** 2022-12-17 23:20 UTC
Labels: python validator, community rules, new rule
