### ISSUE TITLE
Build error:  Task :web:service:compileJava FAILED - can't find Sentry

### ISSUE THREAD

**Issue by briandonahue** [MobilityData/gtfs-validator#1394] opened 2023-04-20 00:39 UTC
### Describe the bug

When running `./gradleW build` or building from an IDE, the sentry dependency is not found:

```
> Task :web:service:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web:service:compileJava'.
> Could not resolve all files for configuration ':web:service:compileClasspath'.
   > Could not resolve io.sentry:sentry-spring:1.7.30.
     Required by:
         project :web:service
      > Could not resolve io.sentry:sentry-spring:1.7.30.
         > Could not get resource 'https://repo.maven.apache.org/maven2/io/sentry/sentry-spring/1.7.30/sentry-spring-1.7.30.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/io/sentry/sentry-spring/1.7.30/sentry-spring-1.7.30.pom'.
               > repo.maven.apache.org

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Says it can't find repo.maven.apache.org. I assume this is related to #1384 

### Steps/Code to Reproduce

Run `./gradleW build` in projec root.

### Expected Results

Should build without error.

### Actual Results

```
> Task :web:service:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web:service:compileJava'.
> Could not resolve all files for configuration ':web:service:compileClasspath'.
   > Could not resolve io.sentry:sentry-spring:1.7.30.
     Required by:
         project :web:service
      > Could not resolve io.sentry:sentry-spring:1.7.30.
         > Could not get resource 'https://repo.maven.apache.org/maven2/io/sentry/sentry-spring/1.7.30/sentry-spring-1.7.30.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/io/sentry/sentry-spring/1.7.30/sentry-spring-1.7.30.pom'.
               > repo.maven.apache.org

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Screenshots

<img width="929" alt="image" src="https://user-images.githubusercontent.com/40084/233228003-87f31756-15c6-400b-8f0e-567e11c05d1d.png">

### Validator version

master branch

### Operating system

MacOS, M1

### Java version

11.0.18

**Comment by davidgamez** [comment] 2023-04-20 20:00
@briandonahue let's connect to understand better the root cause.

**Comment by KClough** [comment] 2023-04-20 20:04
@davidgamez When I implemented this originally, I used a legacy version of the Sentry API to support the version of the JDK we are currently using. 

I haven't confirmed this, but it looks like this version may have been delisted from the gradle repository? 

I did some testing today with a newer version of Sentry that is designed for spring-boot applications which doesn't appear to have a hard JDK version requirement.

I'm waiting on the new Sentry credentials so I can confirm this version is capturing errors as expected before pushing a PR with the Sentry change.

**Comment by davidgamez** [comment] 2023-04-20 21:01
> @davidgamez When I implemented this originally, I used a legacy version of the Sentry API to support the version of the JDK we are currently using.
> 
> I haven't confirmed this, but it looks like this version may have been delisted from the gradle repository?
> 
> I did some testing today with a newer version of Sentry that is designed for spring-boot applications which doesn't appear to have a hard JDK version requirement.
> 
> I'm waiting on the new Sentry credentials so I can confirm this version is capturing errors as expected before pushing a PR with the Sentry change.

I tested locally via terminal and IDEs and both worked without issues. It's also working in the GithubActions. I'm wondering if this is related to an IDE misconfigured for gradle or a corrupt gradle cache somewhere.

**Comment by briandonahue** [comment] 2023-04-21 13:47
> I tested locally via terminal and IDEs and both worked without issues. It's also working in the GithubActions. I'm wondering if this is related to an IDE misconfigured for gradle or a corrupt gradle cache somewhere.

@davidgamez I will message you in Slack and we can debug on my machine.

**Comment by isabelle-dr** [comment] 2023-04-21 15:12
@briandonahue is this solved?

**Comment by davidgamez** [comment] 2023-04-21 15:42
@briandonahue and I connected and it seems with the latest main code, we are unable to replicate the issue. We tested current local environments and clean local environments. We agreed in closing the issue and open it again if needed.

**Closed by davidgamez** 2023-04-21 15:42 UTC
Labels: bug, status: Needs triage
