### ISSUE TITLE
Links from the HTML documentation to the online documentation are not working

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-validator#1626] opened 2023-12-20 19:22 UTC
### Describe the bug

The HTML report provides links to our online documentation via a "You can see more about this notice here" statement. 

These links are structured as https://gtfs-validator.mobilitydata.org/rules.html#notice_name in the report.
- example: https://gtfs-validator.mobilitydata.org/rules.html#missing_recommended_file

The anchors in the documentation are structured as https://gtfs-validator.mobilitydata.org/rules.html#notice_name-rule
- example: https://gtfs-validator.mobilitydata.org/rules.html#missing_recommended_file-rule

The missing `-rule` at the end means the links on the HTML report bring the users to the top of the documentation page as a result instead of to the exact location of the rule doc.

### Steps/Code to Reproduce

- Validate any GTFS dataset
- Expand a rule and click on the link that redirects to our online documentation

### Expected Results

I land directly at the location of the rule in the doc

### Actual Results

I land at the top of the document

### Validator version

4.2.1

### Operating system

MacOS

**Comment by bradyhunsaker** [comment] 2024-01-02 16:47
Looks like this and issue #1608 are duplicates.

**Comment by jcpitre** [comment] 2024-01-03 16:04
Duplicate of https://github.com/MobilityData/gtfs-validator/issues/1608

**Closed by jcpitre** 2024-01-03 16:04 UTC
Labels: bug, status: Needs triage
